In [1]:
import pandas as pd

In [2]:
luke_new_metadata = pd.read_csv(
    "/Users/michael/Data/Luke_terrace_experiment/Microbiome/lic2024_pooled_meta.tsv",
    sep="\t",
    skiprows=[1],
)
luke_new_metadata

    sample-id sample.type timepoint     date  time platename  daysincestart
0      LIC001       plant       t01  11/1/23  8:00    LIC_01              0
1      LIC002       plant       t01  11/1/23  8:00    LIC_01              0
2      LIC003       plant       t01  11/1/23  8:00    LIC_01              0
3      LIC004       plant       t01  11/1/23  8:00    LIC_01              0
4      LIC005       plant       t01  11/1/23  8:00    LIC_01              0
..        ...         ...       ...      ...   ...       ...            ...
603  t24_soil        soil       t24   3/1/24  8:00    LIC_04            121
604  t25_soil        soil       t25   3/5/24  8:00    LIC_04            125
605  t26_soil        soil       t26   3/8/24  8:00    LIC_04            128
606  t27_soil        soil       t27  3/12/24  8:00    LIC_04            132
607  t28_soil        soil       t28  3/14/24  8:00    LIC_04            134

[608 rows x 7 columns]

In [3]:
full_meta_data = pd.read_csv(
    "/Users/michael/Git/Outdoor_microbiome/Local_analysis/Plates_1_to_5_metadata.csv"
)
# full_meta_data = full_meta_data.set_index('filename', drop = True)
full_meta_data = full_meta_data.drop_duplicates()
full_meta_data["Experiment Type"] = full_meta_data["timepoint"].str.split("t").str[0]
full_meta_data = full_meta_data.replace("", "Long Term")
full_meta_data = full_meta_data.replace("c1_", "Circadian Experiment 1")
full_meta_data = full_meta_data.replace("c2_", "Circadian Experiment 2")
full_meta_data["Sample Month"] = full_meta_data["date"].str.split("/").str[0]
full_meta_data = full_meta_data.replace(
    {
        "11": "November",
        "12": "December",
        "1": "January",
        "2": "February",
        "3": "March",
        "4": "April",
    }
)
full_meta_data

,filename,plate.pos,arb.sort,sampID,sample.type,timepoint,date,time,extractplate,rnaprepplate,...,Multimapping,No Feature,Ambiguous Unstranded,Ambiguous Forward,plate_row,plate_col,Total Reads,Unmapped Over Mapped,Experiment Type,Sample Month
0,A2450525897_n01_LICRNA01_A01,A01,1,LIC001,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01,...,334817.0,112554.0,202285.0,22008.0,A,1,2248661.0,1.170940,Long Term,November
1,A2450525897_n01_LICRNA01_B01,B01,2,LIC002,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01,...,776239.0,226718.0,494847.0,49830.0,B,1,5984566.0,0.847878,Long Term,November
2,A2450525897_n01_LICRNA01_C01,C01,3,LIC003,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01,...,427910.0,97848.0,271449.0,28416.0,C,1,2936453.0,0.777471,Long Term,November
3,A2450525897_n01_LICRNA01_D01,D01,4,LIC004,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01,...,177674.0,49095.0,123691.0,13452.0,D,1,1359823.0,0.929141,Long Term,November
4,A2450525897_n01_LICRNA01_E01,E01,5,LIC005,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01,...,309156.0,135512.0,229101.0,26474.0,E,1,2680737.0,1.120708,Long Term,November
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,A2534491401_n01_LICRNA05_D12,D12,92,LIC542,plant,c1_t13,2/11/24,20:00,LICCIRC_02,LICRNA_05,...,813353.0,383610.0,550523.0,68933.0,D,12,6510475.0,0.661059,Circadian Experiment 1,February
476,A2534491401_n01_LICRNA05_E12,E12,93,LIC495,plant,c1_t09,2/11/24,4:00,LICCIRC_02,LICRNA_05,...,923444.0,451686.0,560171.0,67290.0,E,12,6178604.0,0.684918,Circadian Experiment 1,February
477,A2534491401_n01_LICRNA05_F12,F12,94,LIC421,plant,c1_t04,2/10/24,8:00,LICCIRC_01,LICRNA_05,...,877561.0,360911.0,638643.0,80102.0,F,12,7035335.0,0.694405,Circadian Experiment 1,February
478,A2534491401_n01_LICRNA05_G12,G12,95,LIC493,plant,c1_t09,2/11/24,4:00,LICCIRC_02,LICRNA_05,...,931512.0,518084.0,1005149.0,113565.0,G,12,11812634.0,0.514605,Circadian Experiment 1,February
479,A2534491401_n01_LICRNA05_H12,H12,96,LIC505,plant,c1_t10,2/11/24,8:00,LICCIRC_02,LICRNA_05,...,945993.0,647515.0,873351.0,100264.0,H,12,9668187.0,0.562464,Circadian Experiment 1,February

In [4]:
old_metadata = full_meta_data

In [5]:
plant_luke_metadata = luke_new_metadata.loc[luke_new_metadata["sample.type"] == "plant"]
plant_luke_metadata.tail(20)

    sample-id sample.type timepoint    date   time   platename  daysincestart
522    LIC725       plant    c2_t11  3/3/24  12:00  LICCIRC_04            123
523    LIC726       plant    c2_t11  3/3/24  12:00  LICCIRC_04            123
524    LIC727       plant    c2_t11  3/3/24  12:00  LICCIRC_04            123
525    LIC728       plant    c2_t11  3/3/24  12:00  LICCIRC_04            123
526    LIC733       plant    c2_t12  3/3/24  16:00  LICCIRC_04            123
527    LIC734       plant    c2_t12  3/3/24  16:00  LICCIRC_04            123
528    LIC735       plant    c2_t12  3/3/24  16:00  LICCIRC_04            123
529    LIC736       plant    c2_t12  3/3/24  16:00  LICCIRC_04            123
530    LIC737       plant    c2_t12  3/3/24  16:00  LICCIRC_04            123
531    LIC738       plant    c2_t12  3/3/24  16:00  LICCIRC_04            123
532    LIC739       plant    c2_t12  3/3/24  16:00  LICCIRC_04            123
533    LIC740       plant    c2_t12  3/3/24  16:00  LICCIRC_04            123
534    LIC745       plant    c2_t13  3/3/24  20:00  LICCIRC_04            123
535    LIC746       plant    c2_t13  3/3/24  20:00  LICCIRC_04            123
536    LIC747       plant    c2_t13  3/3/24  20:00  LICCIRC_04            123
537    LIC748       plant    c2_t13  3/3/24  20:00  LICCIRC_04            123
538    LIC749       plant    c2_t13  3/3/24  20:00  LICCIRC_04            123
539    LIC750       plant    c2_t13  3/3/24  20:00  LICCIRC_04            123
540    LIC751       plant    c2_t13  3/3/24  20:00  LICCIRC_04            123
541    LIC752       plant    c2_t13  3/3/24  20:00  LICCIRC_04            123

In [8]:
merged_meta_data_first_4_plates

,filename,plate.pos,arb.sort,sampID,sample.type,timepoint,date,time,extractplate,rnaprepplate,...,Ambiguous Unstranded,Ambiguous Forward,plate_row,plate_col,Total Reads,Unmapped Over Mapped,Experiment Type,Sample Month,sample-id,daysincestart
0,A2450525897_n01_LICRNA01_A01,A01,1,LIC001,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01,...,202285.0,22008.0,A,1,2248661.0,1.170940,Long Term,November,LIC001,0
1,A2450525897_n01_LICRNA01_B01,B01,2,LIC002,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01,...,494847.0,49830.0,B,1,5984566.0,0.847878,Long Term,November,LIC002,0
2,A2450525897_n01_LICRNA01_C01,C01,3,LIC003,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01,...,271449.0,28416.0,C,1,2936453.0,0.777471,Long Term,November,LIC003,0
3,A2450525897_n01_LICRNA01_D01,D01,4,LIC004,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01,...,123691.0,13452.0,D,1,1359823.0,0.929141,Long Term,November,LIC004,0
4,A2450525897_n01_LICRNA01_E01,E01,5,LIC005,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01,...,229101.0,26474.0,E,1,2680737.0,1.120708,Long Term,November,LIC005,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,A2534491401_n01_LICRNA05_D12,D12,92,LIC542,plant,c1_t13,2/11/24,20:00,LICCIRC_02,LICRNA_05,...,550523.0,68933.0,D,12,6510475.0,0.661059,Circadian Experiment 1,February,LIC542,102
476,A2534491401_n01_LICRNA05_E12,E12,93,LIC495,plant,c1_t09,2/11/24,4:00,LICCIRC_02,LICRNA_05,...,560171.0,67290.0,E,12,6178604.0,0.684918,Circadian Experiment 1,February,LIC495,102
477,A2534491401_n01_LICRNA05_F12,F12,94,LIC421,plant,c1_t04,2/10/24,8:00,LICCIRC_01,LICRNA_05,...,638643.0,80102.0,F,12,7035335.0,0.694405,Circadian Experiment 1,February,LIC421,101
478,A2534491401_n01_LICRNA05_G12,G12,95,LIC493,plant,c1_t09,2/11/24,4:00,LICCIRC_02,LICRNA_05,...,1005149.0,113565.0,G,12,11812634.0,0.514605,Circadian Experiment 1,February,LIC493,102
479,A2534491401_n01_LICRNA05_H12,H12,96,LIC505,plant,c1_t10,2/11/24,8:00,LICCIRC_02,LICRNA_05,...,873351.0,100264.0,H,12,9668187.0,0.562464,Circadian Experiment 1,February,LIC505,102

In [7]:
merged_meta_data_first_4_plates = old_metadata.merge(
    luke_new_metadata[["sample-id", "daysincestart"]],
    left_on="sampID",
    right_on="sample-id",
)
merged_meta_data_first_4_plates.to_csv(
    "/Users/michael/Data/Luke_terrace_experiment/General_data/Plates_1_to_5_metadata_merged_luke.csv",
    index=False,
)