In [2]:
import pandas as pd
import Go_tools

In [ ]:
arabi_go_matrix = pd.read_csv(
    "/Users/michael/Data/Reference_data/Arabdidopsis_go_matrix_from_tair_gaf.csv",
    index_col=0,
)
arabi_go_matrix
defense_terms = pd.read_csv(
    "/Users/michael/Data/Luke_terrace_experiment/General_data/Defense_go_terms.csv"
)
defense_terms

,GO:0000001,GO:0000009,GO:0000012,GO:0000014,GO:0000023,GO:0000024,GO:0000025,GO:0000026,GO:0000027,GO:0000028,...,GO:2001071,GO:2001080,GO:2001141,GO:2001142,GO:2001143,GO:2001147,GO:2001227,GO:2001280,GO:2001289,GO:2001294
GeneID,,,,,,,,,,,,,,,,,,,,,
AT1G01010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AT1G01020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AT1G01030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AT1G01040,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AT1G01046,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AT5G67600,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AT5G67610,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AT5G67620,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AT5G67630,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AT5G67640,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
# Extract unique GO terms from defense_terms
go_terms = defense_terms["GO Term ID"].unique()
print(f"Found {len(go_terms)} unique GO terms")
print(go_terms)

Found 12 unique GO terms
['GO:0012501' 'GO:0009626' 'GO:0042742' 'GO:0071219' 'GO:0045087'
 'GO:0009862' 'GO:0009861' 'GO:0034055' 'GO:0009682' 'GO:0009627'
 'GO:0002237' 'GO:0010421']

In [9]:
from itertools import combinations

# Create a dictionary mapping GO terms to their genes
go_to_genes = {}
for go_term in go_terms:
    # Get genes that have this GO term (columns with value 1)
    genes = arabi_go_matrix[arabi_go_matrix[go_term] == 1].index.tolist()
    go_to_genes[go_term] = set(genes)
    print(f"{go_term}: {len(genes)} genes")

print(f"\nTotal GO terms: {len(go_to_genes)}")

# Generate all possible combinations of GO terms
# Get all combinations of different sizes
all_combinations = {}
for r in range(1, len(go_terms) + 1):
    for combo in combinations(go_terms, r):
        # Find union of genes for this combination
        gene_sets = [go_to_genes[term] for term in combo]
        combined_genes = set.union(*gene_sets)
        combo_key = " OR ".join(combo)
        all_combinations[combo_key] = combined_genes

# Filter to only keep combinations with more than 20 genes
filtered_combinations = {k: v for k, v in all_combinations.items() if len(v) > 20}

print(f"\nGenerated {len(all_combinations)} combinations")
print(f"Filtered to {len(filtered_combinations)} combinations with >20 genes")
print("\nCombinations with gene counts:")
for combo_key, genes in sorted(
    filtered_combinations.items(), key=lambda x: len(x[1]), reverse=True
):
    print(f"  {combo_key}: {len(genes)} genes")

GO:0012501: 34 genes
GO:0009626: 54 genes
GO:0042742: 325 genes
GO:0071219: 7 genes
GO:0045087: 58 genes
GO:0009862: 16 genes
GO:0009861: 11 genes
GO:0034055: 1 genes
GO:0009682: 21 genes
GO:0009627: 57 genes
GO:0002237: 41 genes
GO:0010421: 2 genes

Total GO terms: 12

Generated 4095 combinations
Filtered to 4077 combinations with >20 genes

Combinations with gene counts:
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 515 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 514 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 514 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237: 513 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 512 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 512 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 511 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 511 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 511 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 511 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237: 510 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237: 510 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 509 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0002237 OR GO:0010421: 509 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 508 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 508 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0002237: 508 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009627 OR GO:0002237 OR GO:0010421: 508 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 508 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237: 507 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009627 OR GO:0002237: 507 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 507 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 507 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009682 OR GO:0009627 OR GO:0002237: 506 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0002237 OR GO:0010421: 506 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0002237: 505 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009627 OR GO:0002237 OR GO:0010421: 505 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0002237 OR GO:0010421: 505 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 505 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009627 OR GO:0002237: 504 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0002237: 504 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0009627 OR GO:0002237 OR GO:0010421: 504 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 504 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 504 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 504 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0009627 OR GO:0002237: 503 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009682 OR GO:0009627 OR GO:0002237: 503 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 503 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 503 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009682 OR GO:0009627 OR GO:0002237: 502 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0002237 OR GO:0010421: 502 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0034055 OR GO:0009627 OR GO:0002237 OR GO:0010421: 502 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0002237: 501 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009861 OR GO:0009627 OR GO:0002237 OR GO:0010421: 501 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0034055 OR GO:0009627 OR GO:0002237: 501 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009627 OR GO:0002237 OR GO:0010421: 501 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 501 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009861 OR GO:0009627 OR GO:0002237: 500 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009627 OR GO:0002237: 500 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 500 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 500 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009682 OR GO:0009627 OR GO:0002237: 499 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0034055 OR GO:0009627 OR GO:0002237 OR GO:0010421: 499 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0034055 OR GO:0009627 OR GO:0002237: 498 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009627 OR GO:0002237 OR GO:0010421: 498 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009627 OR GO:0002237: 497 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0034055 OR GO:0009627 OR GO:0002237 OR GO:0010421: 497 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0034055 OR GO:0009627 OR GO:0002237: 496 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009627 OR GO:0002237 OR GO:0010421: 496 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009627 OR GO:0002237: 495 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 495 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0034055 OR GO:0009627 OR GO:0002237 OR GO:0010421: 494 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 494 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0034055 OR GO:0009627 OR GO:0002237: 493 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009627 OR GO:0002237 OR GO:0010421: 493 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 493 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009627 OR GO:0002237: 492 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237: 492 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 492 genes
  GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 492 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 491 genes
  GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 491 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 490 genes
  GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 490 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0010421: 490 genes
  GO:0012501 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 490 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237: 489 genes
  GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237: 489 genes
  GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 489 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627: 489 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0010421: 489 genes
  GO:0012501 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 489 genes
  GO:0012501 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 489 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0002237 OR GO:0010421: 489 genes
  GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 488 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009682 OR GO:0009627: 488 genes
  GO:0012501 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237: 488 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009627 OR GO:0002237 OR GO:0010421: 488 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 488 genes
  GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 487 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0002237: 487 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 487 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0010421: 487 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0010421: 487 genes
  GO:0012501 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 487 genes
  GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237: 486 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009627 OR GO:0002237: 486 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627: 486 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0010421: 486 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627: 486 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0010421: 486 genes
  GO:0012501 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 486 genes
  GO:0012501 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 486 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 486 genes
  GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0002237 OR GO:0010421: 486 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0009682 OR GO:0009627: 485 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009682 OR GO:0009627: 485 genes
  GO:0012501 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237: 485 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009682 OR GO:0009627 OR GO:0002237: 485 genes
  GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009627 OR GO:0002237 OR GO:0010421: 485 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0002237 OR GO:0010421: 485 genes
  GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 485 genes
  GO:0012501 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 485 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0009627 OR GO:0002237 OR GO:0010421: 484 genes
  GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0002237: 484 genes
  GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 484 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0010421: 484 genes
  GO:0012501 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 484 genes
  GO:0012501 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 484 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 484 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0010421: 484 genes
  GO:0012501 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0002237 OR GO:0010421: 484 genes
  GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009627 OR GO:0002237: 483 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009682 OR GO:0009627: 483 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0010421: 483 genes
  GO:0012501 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0009682 OR GO:0009627 OR GO:0002237: 483 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0002237: 483 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 483 genes
  GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 483 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009627: 483 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009627 OR GO:0010421: 483 genes
  GO:0012501 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0002237: 483 genes
  GO:0012501 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009627 OR GO:0002237 OR GO:0010421: 483 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0010421: 483 genes
  GO:0012501 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237 OR GO:0010421: 483 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009861 OR GO:0009682 OR GO:0009627: 482 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009861 OR GO:0009627 OR GO:0002237: 482 genes
  GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009862 OR GO:0009682 OR GO:0009627 OR GO:0002237: 482 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009627: 482 genes
  GO:0012501 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009861 OR GO:0009627 OR GO:0002237: 482 genes
  GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 482 genes
  GO:0009626 OR GO:0042742 OR GO:0045087 OR GO:0009861 OR GO:0034055 OR GO:0009627 OR GO:0002237 OR GO:0010421: 482 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0034055 OR GO:0009682 OR GO:0009627: 482 genes
  GO:0012501 OR GO:0009626 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0009682 OR GO:0009627 OR GO:0010421: 482 genes
  GO:0012501 OR GO:0042742 OR GO:0071219 OR GO:0045087 OR GO:0009862 OR GO:0034055 OR GO:0009682 OR GO:0009627 OR GO:0002237: 482 genes

In [10]:
filtered_combinations

{'GO:0012501': {'AT1G08720',
  'AT1G12220',
  'AT1G13680',
  'AT1G16420',
  'AT1G26630',
  'AT1G29690',
  'AT1G29850',
  'AT1G32230',
  'AT1G64280',
  'AT1G73260',
  'AT2G19860',
  'AT2G26560',
  'AT2G36010',
  'AT2G38530',
  'AT2G41060',
  'AT3G06490',
  'AT3G15010',
  'AT3G16770',
  'AT3G20210',
  'AT3G27060',
  'AT3G44880',
  'AT3G45860',
  'AT3G50930',
  'AT3G56860',
  'AT4G23130',
  'AT4G23170',
  'AT4G23280',
  'AT4G29130',
  'AT4G35790',
  'AT4G38360',
  'AT5G02190',
  'AT5G10380',
  'AT5G43940',
  'AT5G51290'},
 'GO:0009626': {'AT1G02860',
  'AT1G08450',
  'AT1G12220',
  'AT1G19250',
  'AT1G28380',
  'AT1G29340',
  'AT1G29690',
  'AT1G59870',
  'AT1G71220',
  'AT2G13790',
  'AT2G20310',
  'AT2G26560',
  'AT3G07040',
  'AT3G20600',
  'AT3G21220',
  'AT3G25070',
  'AT3G28910',
  'AT3G44670',
  'AT3G46530',
  'AT3G48090',
  'AT3G50930',
  'AT3G52430',
  'AT3G54420',
  'AT3G55830',
  'AT4G02640',
  'AT4G03110',
  'AT4G12720',
  'AT4G19660',
  'AT4G20380',
  'AT4G23210',
  'AT4G26090',
  'AT4G33430',
  'AT4G36280',
  'AT4G36290',
  'AT4G37930',
  'AT4G37980',
  'AT4G37990',
  'AT5G10530',
  'AT5G15410',
  'AT5G20480',
  'AT5G22290',
  'AT5G43470',
  'AT5G44870',
  'AT5G45110',
  'AT5G45250',
  'AT5G45260',
  'AT5G46180',
  'AT5G48380',
  'AT5G50260',
  'AT5G51700',
  'AT5G54250',
  'AT5G61900',
  'AT5G64930',
  'AT5G65600'},
 'GO:0042742': {'AT1G01100',
  'AT1G01230',
  'AT1G02120',
  'AT1G02205',
  'AT1G02450',
  'AT1G02860',
  'AT1G02920',
  'AT1G04510',
  'AT1G06580',
  'AT1G07360',
  'AT1G08060',
  'AT1G08450',
  'AT1G08830',
  'AT1G09770',
  'AT1G10170',
  'AT1G11350',
  'AT1G12220',
  'AT1G15530',
  'AT1G16540',
  'AT1G17615',
  'AT1G17750',
  'AT1G18350',
  'AT1G18570',
  'AT1G18670',
  'AT1G19180',
  'AT1G19250',
  'AT1G19350',
  'AT1G19670',
  'AT1G20580',
  'AT1G20850',
  'AT1G21110',
  'AT1G21120',
  'AT1G22070',
  'AT1G22882',
  'AT1G22885',
  'AT1G22890',
  'AT1G24100',
  'AT1G26380',
  'AT1G26410',
  'AT1G26420',
  'AT1G26630',
  'AT1G27320',
  'AT1G28520',
  'AT1G31280',
  'AT1G31350',
  'AT1G31580',
  'AT1G31770',
  'AT1G32230',
  'AT1G33520',
  'AT1G33560',
  'AT1G33980',
  'AT1G35230',
  'AT1G48480',
  'AT1G48490',
  'AT1G48630',
  'AT1G48830',
  'AT1G51890',
  'AT1G52740',
  'AT1G53130',
  'AT1G53940',
  'AT1G54040',
  'AT1G55020',
  'AT1G59820',
  'AT1G59870',
  'AT1G61580',
  'AT1G64170',
  'AT1G64280',
  'AT1G64550',
  'AT1G64790',
  'AT1G65500',
  'AT1G65930',
  'AT1G66340',
  'AT1G66700',
  'AT1G69170',
  'AT1G69220',
  'AT1G69370',
  'AT1G70560',
  'AT1G70690',
  'AT1G73260',
  'AT1G73805',
  'AT1G74710',
  'AT1G76080',
  'AT1G76300',
  'AT1G76930',
  'AT1G77920',
  'AT1G79380',
  'AT1G80460',
  'AT1G80600',
  'AT1G80840',
  'AT2G01830',
  'AT2G03445',
  'AT2G05940',
  'AT2G13810',
  'AT2G17520',
  'AT2G18790',
  'AT2G19190',
  'AT2G19990',
  'AT2G20310',
  'AT2G22240',
  'AT2G22300',
  'AT2G22330',
  'AT2G23150',
  'AT2G24570',
  'AT2G25000',
  'AT2G25110',
  'AT2G25470',
  'AT2G26330',
  'AT2G26870',
  'AT2G27040',
  'AT2G27050',
  'AT2G27080',
  'AT2G28830',
  'AT2G30750',
  'AT2G30770',
  'AT2G30880',
  'AT2G32680',
  'AT2G33340',
  'AT2G34690',
  'AT2G37630',
  'AT2G38470',
  'AT2G39050',
  'AT2G39200',
  'AT2G39260',
  'AT2G39770',
  'AT2G39940',
  'AT2G40000',
  'AT2G40750',
  'AT2G41560',
  'AT2G41760',
  'AT2G42010',
  'AT2G43120',
  'AT2G43700',
  'AT2G43710',
  'AT2G43790',
  'AT2G44490',
  'AT2G46400',
  'AT2G47130',
  'AT3G01420',
  'AT3G01680',
  'AT3G02080',
  'AT3G04720',
  'AT3G05200',
  'AT3G07525',
  'AT3G08510',
  'AT3G09200',
  'AT3G09830',
  'AT3G10525',
  'AT3G10930',
  'AT3G11250',
  'AT3G12810',
  'AT3G14130',
  'AT3G14150',
  'AT3G14310',
  'AT3G14415',
  'AT3G14420',
  'AT3G14460',
  'AT3G17210',
  'AT3G18165',
  'AT3G19190',
  'AT3G20600',
  'AT3G20770',
  'AT3G21630',
  'AT3G23400',
  'AT3G25070',
  'AT3G28930',
  'AT3G28940',
  'AT3G30775',
  'AT3G43300',
  'AT3G44260',
  'AT3G44670',
  'AT3G44880',
  'AT3G45860',
  'AT3G46280',
  'AT3G46510',
  'AT3G46930',
  'AT3G47520',
  'AT3G49110',
  'AT3G49120',
  'AT3G50260',
  'AT3G50950',
  'AT3G52430',
  'AT3G53810',
  'AT3G54560',
  'AT3G54640',
  'AT3G55550',
  'AT3G56400',
  'AT3G56710',
  'AT3G57330',
  'AT3G57710',
  'AT3G57730',
  'AT3G59700',
  'AT3G59740',
  'AT4G00830',
  'AT4G00990',
  'AT4G02420',
  'AT4G03550',
  'AT4G11650',
  'AT4G11850',
  'AT4G12010',
  'AT4G12490',
  'AT4G12500',
  'AT4G12720',
  'AT4G14400',
  'AT4G14465',
  'AT4G15900',
  'AT4G16890',
  'AT4G18360',
  'AT4G18780',
  'AT4G19660',
  'AT4G19700',
  'AT4G22305',
  'AT4G22330',
  'AT4G23100',
  'AT4G23130',
  'AT4G23190',
  'AT4G23210',
  'AT4G23270',
  'AT4G23280',
  'AT4G23810',
  'AT4G24230',
  'AT4G24670',
  'AT4G25030',
  'AT4G25890',
  'AT4G26070',
  'AT4G26090',
  'AT4G26850',
  'AT4G28420',
  'AT4G28460',
  'AT4G31500',
  'AT4G31550',
  'AT4G31750',
  'AT4G31800',
  'AT4G33300',
  'AT4G33430',
  'AT4G33925',
  'AT4G33950',
  'AT4G34390',
  'AT4G35230',
  'AT4G35450',
  'AT4G36290',
  'AT4G37460',
  'AT4G38130',
  'AT4G39030',
  'AT4G39090',
  'AT4G39950',
  'AT5G01540',
  'AT5G01900',
  'AT5G02310',
  'AT5G02500',
  'AT5G03280',
  'AT5G04720',
  'AT5G05300',
  'AT5G06320',
  'AT5G09230',
  'AT5G10030',
  'AT5G11270',
  'AT5G11630',
  'AT5G12380',
  'AT5G13160',
  'AT5G13320',
  'AT5G14545',
  'AT5G14565',
  'AT5G17880',
  'AT5G18370',
  'AT5G18525',
  'AT5G20010',
  'AT5G22250',
  'AT5G22540',
  'AT5G22570',
  'AT5G23570',
  'AT5G24110',
  'AT5G24210',
  'AT5G24360',
  'AT5G24400',
  'AT5G24530',
  'AT5G24660',
  'AT5G26920',
  'AT5G27420',
  'AT5G28040',
  'AT5G33340',
  'AT5G37055',
  'AT5G40770',
  'AT5G40990',
  'AT5G42000',
  'AT5G42120',
  'AT5G42350',
  'AT5G42810',
  'AT5G44030',
  'AT5G44070',
  'AT5G44510',
  'AT5G44568',
  'AT5G45050',
  'AT5G45060',
  'AT5G45110',
  'AT5G45250',
  'AT5G45260',
  'AT5G45410',
  'AT5G46050',
  'AT5G46180',
  'AT5G46330',
  'AT5G46350',
  'AT5G46470',
  'AT5G47010',
  'AT5G48380',
  'AT5G49520',
  'AT5G51700',
  'AT5G52640',
  'AT5G52830',
  'AT5G53120',
  'AT5G56030',
  'AT5G56360',
  'AT5G56980',
  'AT5G57220',
  'AT5G58430',
  'AT5G59830',
  'AT5G59890',
  'AT5G61170',
  'AT5G63840',
  'AT5G63970',
  'AT5G64440',
  'AT5G64810',
  'AT5G65210',
  'AT5G67300',
  'AT5G67330',
  'AT5G67385'},
 'GO:0045087': {'AT1G04300',
  'AT1G08030',
  'AT1G09970',
  'AT1G17250',
  'AT1G20580',
  'AT1G27130',
  'AT1G42540',
  'AT1G48410',
  'AT1G49800',
  'AT1G51940',
  'AT1G55250',
  'AT1G61380',
  'AT1G62045',
  'AT1G64790',
  'AT1G73080',
  'AT1G79090',
  'AT2G02220',
  'AT2G20580',
  'AT2G21660',
  'AT2G22000',
  'AT2G23270',
  'AT2G23770',
  'AT2G24860',
  'AT2G27250',
  'AT2G33580',
  'AT2G35110',
  'AT2G37220',
  'AT2G43850',
  'AT2G44950',
  'AT3G04210',
  'AT3G16030',
  'AT3G21630',
  'AT3G30720',
  'AT3G43300',
  'AT4G00830',
  'AT4G11850',
  'AT4G24770',
  'AT4G28460',
  'AT4G29040',
  'AT4G37290',
  'AT4G39030',
  'AT4G39260',
  'AT5G05680',
  'AT5G05780',
  'AT5G09976',
  'AT5G09978',
  'AT5G09980',
  'AT5G09990',
  'AT5G13160',
  'AT5G18610',
  'AT5G37770',
  'AT5G43560',
  'AT5G47070',
  'AT5G50250',
  'AT5G54610',
  'AT5G64890',
  'AT5G64900',
  'AT5G64905'},
 'GO:0009682': {'AT1G18570',
  'AT1G32960',
  'AT1G64280',
  'AT1G64790',
  'AT2G22330',
  'AT2G30750',
  'AT2G30770',
  'AT2G44490',
  'AT3G56400',
  'AT4G12470',
  'AT4G12480',
  'AT4G18760',
  'AT4G24180',
  'AT4G31500',
  'AT4G31550',
  'AT4G39950',
  'AT5G07690',
  'AT5G11270',
  'AT5G51200',
  'AT5G57220',
  'AT5G61420'},
 'GO:0009627': {'AT1G02860',
  'AT1G09750',
  'AT1G19250',
  'AT1G29660',
  'AT1G49540',
  'AT1G55490',
  'AT1G59870',
  'AT1G64280',
  'AT1G64790',
  'AT1G74710',
  'AT1G75040',
  'AT2G13810',
  'AT2G14610',
  'AT2G18660',
  'AT2G19520',
  'AT2G23560',
  'AT2G23620',
  'AT2G37870',
  'AT2G38470',
  'AT2G40690',
  'AT2G43570',
  'AT2G46370',
  'AT3G01420',
  'AT3G04720',
  'AT3G04740',
  'AT3G05180',
  'AT3G07450',
  'AT3G07690',
  'AT3G10390',
  'AT3G12250',
  'AT3G18490',
  'AT3G48090',
  'AT3G48430',
  'AT3G52430',
  'AT3G53980',
  'AT3G57260',
  'AT4G12470',
  'AT4G18470',
  'AT4G19660',
  'AT4G23170',
  'AT4G25050',
  'AT4G30380',
  'AT4G37150',
  'AT5G03350',
  'AT5G05680',
  'AT5G05960',
  'AT5G10760',
  'AT5G40990',
  'AT5G45110',
  'AT5G48485',
  'AT5G48490',
  'AT5G52810',
  'AT5G55410',
  'AT5G55450',
  'AT5G55460',
  'AT5G64570',
  'AT5G64930'},
 'GO:0002237': {'AT1G07000',
  'AT1G08320',
  'AT1G12080',
  'AT1G16670',
  'AT1G26190',
  'AT1G51800',
  'AT1G56160',
  'AT1G59820',
  'AT1G59870',
  'AT1G62810',
  'AT1G66340',
  'AT1G66730',
  'AT1G69220',
  'AT1G73260',
  'AT1G79550',
  'AT1G80460',
  'AT1G80840',
  'AT2G17740',
  'AT2G25000',
  'AT2G32680',
  'AT2G39660',
  'AT2G42490',
  'AT3G05010',
  'AT3G05360',
  'AT3G10490',
  'AT3G22600',
  'AT3G25070',
  'AT3G50930',
  'AT3G55150',
  'AT3G55450',
  'AT3G59280',
  'AT3G59370',
  'AT4G08850',
  'AT4G23210',
  'AT4G26070',
  'AT4G31800',
  'AT5G03280',
  'AT5G06839',
  'AT5G18520',
  'AT5G24590',
  'AT5G26920'},
 'GO:0012501 OR GO:0009626': {'AT1G02860',
  'AT1G08450',
  'AT1G08720',
  'AT1G12220',
  'AT1G13680',
  'AT1G16420',
  'AT1G19250',
  'AT1G26630',
  'AT1G28380',
  'AT1G29340',
  'AT1G29690',
  'AT1G29850',
  'AT1G32230',
  'AT1G59870',
  'AT1G64280',
  'AT1G71220',
  'AT1G73260',
  'AT2G13790',
  'AT2G19860',
  'AT2G20310',
  'AT2G26560',
  'AT2G36010',
  'AT2G38530',
  'AT2G41060',
  'AT3G06490',
  'AT3G07040',
  'AT3G15010',
  'AT3G16770',
  'AT3G20210',
  'AT3G20600',
  'AT3G21220',
  'AT3G25070',
  'AT3G27060',
  'AT3G28910',
  'AT3G44670',
  'AT3G44880',
  'AT3G45860',
  'AT3G46530',
  'AT3G48090',
  'AT3G50930',
  'AT3G52430',
  'AT3G54420',
  'AT3G55830',
  'AT3G56860',
  'AT4G02640',
  'AT4G03110',
  'AT4G12720',
  'AT4G19660',
  'AT4G20380',
  'AT4G23130',
  'AT4G23170',
  'AT4G23210',
  'AT4G23280',
  'AT4G26090',
  'AT4G29130',
  'AT4G33430',
  'AT4G35790',
  'AT4G36280',
  'AT4G36290',
  'AT4G37930',
  'AT4G37980',
  'AT4G37990',
  'AT4G38360',
  'AT5G02190',
  'AT5G10380',
  'AT5G10530',
  'AT5G15410',
  'AT5G20480',
  'AT5G22290',
  'AT5G43470',
  'AT5G43940',
  'AT5G44870',
  'AT5G45110',
  'AT5G45250',
  'AT5G45260',
  'AT5G46180',
  'AT5G48380',
  'AT5G50260',
  'AT5G51290',
  'AT5G51700',
  'AT5G54250',
  'AT5G61900',
  'AT5G64930',
  'AT5G65600'},
 'GO:0012501 OR GO:0042742': {'AT1G01100',
  'AT1G01230',
  'AT1G02120',
  'AT1G02205',
  'AT1G02450',
  'AT1G02860',
  'AT1G02920',
  'AT1G04510',
  'AT1G06580',
  'AT1G07360',
  'AT1G08060',
  'AT1G08450',
  'AT1G08720',
  'AT1G08830',
  'AT1G09770',
  'AT1G10170',
  'AT1G11350',
  'AT1G12220',
  'AT1G13680',
  'AT1G15530',
  'AT1G16420',
  'AT1G16540',
  'AT1G17615',
  'AT1G17750',
  'AT1G18350',
  'AT1G18570',
  'AT1G18670',
  'AT1G19180',
  'AT1G19250',
  'AT1G19350',
  'AT1G19670',
  'AT1G20580',
  'AT1G20850',
  'AT1G21110',
  'AT1G21120',
  'AT1G22070',
  'AT1G22882',
  'AT1G22885',
  'AT1G22890',
  'AT1G24100',
  'AT1G26380',
  'AT1G26410',
  'AT1G26420',
  'AT1G26630',
  'AT1G27320',
  'AT1G28520',
  'AT1G29690',
  'AT1G29850',
  'AT1G31280',
  'AT1G31350',
  'AT1G31580',
  'AT1G31770',
  'AT1G32230',
  'AT1G33520',
  'AT1G33560',
  'AT1G33980',
  'AT1G35230',
  'AT1G48480',
  'AT1G48490',
  'AT1G48630',
  'AT1G48830',
  'AT1G51890',
  'AT1G52740',
  'AT1G53130',
  'AT1G53940',
  'AT1G54040',
  'AT1G55020',
  'AT1G59820',
  'AT1G59870',
  'AT1G61580',
  'AT1G64170',
  'AT1G64280',
  'AT1G64550',
  'AT1G64790',
  'AT1G65500',
  'AT1G65930',
  'AT1G66340',
  'AT1G66700',
  'AT1G69170',
  'AT1G69220',
  'AT1G69370',
  'AT1G70560',
  'AT1G70690',
  'AT1G73260',
  'AT1G73805',
  'AT1G74710',
  'AT1G76080',
  'AT1G76300',
  'AT1G76930',
  'AT1G77920',
  'AT1G79380',
  'AT1G80460',
  'AT1G80600',
  'AT1G80840',
  'AT2G01830',
  'AT2G03445',
  'AT2G05940',
  'AT2G13810',
  'AT2G17520',
  'AT2G18790',
  'AT2G19190',
  'AT2G19860',
  'AT2G19990',
  'AT2G20310',
  'AT2G22240',
  'AT2G22300',
  'AT2G22330',
  'AT2G23150',
  'AT2G24570',
  'AT2G25000',
  'AT2G25110',
  'AT2G25470',
  'AT2G26330',
  'AT2G26560',
  'AT2G26870',
  'AT2G27040',
  'AT2G27050',
  'AT2G27080',
  'AT2G28830',
  'AT2G30750',
  'AT2G30770',
  'AT2G30880',
  'AT2G32680',
  'AT2G33340',
  'AT2G34690',
  'AT2G36010',
  'AT2G37630',
  'AT2G38470',
  'AT2G38530',
  'AT2G39050',
  'AT2G39200',
  'AT2G39260',
  'AT2G39770',
  'AT2G39940',
  'AT2G40000',
  'AT2G40750',
  'AT2G41060',
  'AT2G41560',
  'AT2G41760',
  'AT2G42010',
  'AT2G43120',
  'AT2G43700',
  'AT2G43710',
  'AT2G43790',
  'AT2G44490',
  'AT2G46400',
  'AT2G47130',
  'AT3G01420',
  'AT3G01680',
  'AT3G02080',
  'AT3G04720',
  'AT3G05200',
  'AT3G06490',
  'AT3G07525',
  'AT3G08510',
  'AT3G09200',
  'AT3G09830',
  'AT3G10525',
  'AT3G10930',
  'AT3G11250',
  'AT3G12810',
  'AT3G14130',
  'AT3G14150',
  'AT3G14310',
  'AT3G14415',
  'AT3G14420',
  'AT3G14460',
  'AT3G15010',
  'AT3G16770',
  'AT3G17210',
  'AT3G18165',
  'AT3G19190',
  'AT3G20210',
  'AT3G20600',
  'AT3G20770',
  'AT3G21630',
  'AT3G23400',
  'AT3G25070',
  'AT3G27060',
  'AT3G28930',
  'AT3G28940',
  'AT3G30775',
  'AT3G43300',
  'AT3G44260',
  'AT3G44670',
  'AT3G44880',
  'AT3G45860',
  'AT3G46280',
  'AT3G46510',
  'AT3G46930',
  'AT3G47520',
  'AT3G49110',
  'AT3G49120',
  'AT3G50260',
  'AT3G50930',
  'AT3G50950',
  'AT3G52430',
  'AT3G53810',
  'AT3G54560',
  'AT3G54640',
  'AT3G55550',
  'AT3G56400',
  'AT3G56710',
  'AT3G56860',
  'AT3G57330',
  'AT3G57710',
  'AT3G57730',
  'AT3G59700',
  'AT3G59740',
  'AT4G00830',
  'AT4G00990',
  'AT4G02420',
  'AT4G03550',
  'AT4G11650',
  'AT4G11850',
  'AT4G12010',
  'AT4G12490',
  'AT4G12500',
  'AT4G12720',
  'AT4G14400',
  'AT4G14465',
  'AT4G15900',
  'AT4G16890',
  'AT4G18360',
  'AT4G18780',
  'AT4G19660',
  'AT4G19700',
  'AT4G22305',
  'AT4G22330',
  'AT4G23100',
  'AT4G23130',
  'AT4G23170',
  'AT4G23190',
  'AT4G23210',
  'AT4G23270',
  'AT4G23280',
  'AT4G23810',
  'AT4G24230',
  'AT4G24670',
  'AT4G25030',
  'AT4G25890',
  'AT4G26070',
  'AT4G26090',
  'AT4G26850',
  'AT4G28420',
  'AT4G28460',
  'AT4G29130',
  'AT4G31500',
  'AT4G31550',
  'AT4G31750',
  'AT4G31800',
  'AT4G33300',
  'AT4G33430',
  'AT4G33925',
  'AT4G33950',
  'AT4G34390',
  'AT4G35230',
  'AT4G35450',
  'AT4G35790',
  'AT4G36290',
  'AT4G37460',
  'AT4G38130',
  'AT4G38360',
  'AT4G39030',
  'AT4G39090',
  'AT4G39950',
  'AT5G01540',
  'AT5G01900',
  'AT5G02190',
  'AT5G02310',
  'AT5G02500',
  'AT5G03280',
  'AT5G04720',
  'AT5G05300',
  'AT5G06320',
  'AT5G09230',
  'AT5G10030',
  'AT5G10380',
  'AT5G11270',
  'AT5G11630',
  'AT5G12380',
  'AT5G13160',
  'AT5G13320',
  'AT5G14545',
  'AT5G14565',
  'AT5G17880',
  'AT5G18370',
  'AT5G18525',
  'AT5G20010',
  'AT5G22250',
  'AT5G22540',
  'AT5G22570',
  'AT5G23570',
  'AT5G24110',
  'AT5G24210',
  'AT5G24360',
  'AT5G24400',
  'AT5G24530',
  'AT5G24660',
  'AT5G26920',
  'AT5G27420',
  'AT5G28040',
  'AT5G33340',
  'AT5G37055',
  'AT5G40770',
  'AT5G40990',
  'AT5G42000',
  'AT5G42120',
  'AT5G42350',
  'AT5G42810',
  'AT5G43940',
  'AT5G44030',
  'AT5G44070',
  'AT5G44510',
  'AT5G44568',
  'AT5G45050',
  'AT5G45060',
  'AT5G45110',
  'AT5G45250',
  'AT5G45260',
  'AT5G45410',
  'AT5G46050',
  'AT5G46180',
  'AT5G46330',
  'AT5G46350',
  'AT5G46470',
  'AT5G47010',
  'AT5G48380',
  'AT5G49520',
  'AT5G51290',
  'AT5G51700',
  'AT5G52640',
  'AT5G52830',
  'AT5G53120',
  'AT5G56030',
  'AT5G56360',
  'AT5G56980',
  'AT5G57220',
  'AT5G58430',
  'AT5G59830',
  'AT5G59890',
  'AT5G61170',
  'AT5G63840',
  'AT5G63970',
  'AT5G64440',
  'AT5G64810',
  'AT5G65210',
  'AT5G67300',
  'AT5G67330',
  'AT5G67385'},
 'GO:0012501 OR GO:0071219': {'AT1G08720',
  'AT1G12220',
  'AT1G13680',
  'AT1G16420',
  'AT1G26630',
  'AT1G29690',
  'AT1G29850',
  'AT1G32230',
  'AT1G64280',
  'AT1G73260',
  'AT1G73805',
  'AT2G19860',
  'AT2G23770',
  'AT2G26560',
  'AT2G33550',
  'AT2G36010',
  'AT2G38530',
  'AT2G41060',
  'AT3G06490',
  'AT3G15010',
  'AT3G16770',
  'AT3G20210',
  'AT3G21630',
  'AT3G27060',
  'AT3G44880',
  'AT3G45860',
  'AT3G50930',
  'AT3G56860',
  'AT4G20260',
  'AT4G23130',
  'AT4G23170',
  'AT4G23280',
  'AT4G29130',
  'AT4G35790',
  'AT4G38360',
  'AT5G02190',
  'AT5G10380',
  'AT5G10720',
  'AT5G26920',
  'AT5G43940',
  'AT5G51290'},
 'GO:0012501 OR GO:0045087': {'AT1G04300',
  'AT1G08030',
  'AT1G08720',
  'AT1G09970',
  'AT1G12220',
  'AT1G13680',
  'AT1G16420',
  'AT1G17250',
  'AT1G20580',
  'AT1G26630',
  'AT1G27130',
  'AT1G29690',
  'AT1G29850',
  'AT1G32230',
  'AT1G42540',
  'AT1G48410',
  'AT1G49800',
  'AT1G51940',
  'AT1G55250',
  'AT1G61380',
  'AT1G62045',
  'AT1G64280',
  'AT1G64790',
  'AT1G73080',
  'AT1G73260',
  'AT1G79090',
  'AT2G02220',
  'AT2G19860',
  'AT2G20580',
  'AT2G21660',
  'AT2G22000',
  'AT2G23270',
  'AT2G23770',
  'AT2G24860',
  'AT2G26560',
  'AT2G27250',
  'AT2G33580',
  'AT2G35110',
  'AT2G36010',
  'AT2G37220',
  'AT2G38530',
  'AT2G41060',
  'AT2G43850',
  'AT2G44950',
  'AT3G04210',
  'AT3G06490',
  'AT3G15010',
  'AT3G16030',
  'AT3G16770',
  'AT3G20210',
  'AT3G21630',
  'AT3G27060',
  'AT3G30720',
  'AT3G43300',
  'AT3G44880',
  'AT3G45860',
  'AT3G50930',
  'AT3G56860',
  'AT4G00830',
  'AT4G11850',
  'AT4G23130',
  'AT4G23170',
  'AT4G23280',
  'AT4G24770',
  'AT4G28460',
  'AT4G29040',
  'AT4G29130',
  'AT4G35790',
  'AT4G37290',
  'AT4G38360',
  'AT4G39030',
  'AT4G39260',
  'AT5G02190',
  'AT5G05680',
  'AT5G05780',
  'AT5G09976',
  'AT5G09978',
  'AT5G09980',
  'AT5G09990',
  'AT5G10380',
  'AT5G13160',
  'AT5G18610',
  'AT5G37770',
  'AT5G43560',
  'AT5G43940',
  'AT5G47070',
  'AT5G50250',
  'AT5G51290',
  'AT5G54610',
  'AT5G64890',
  'AT5G64900',
  'AT5G64905'},
 'GO:0012501 OR GO:0009862': {'AT1G08720',
  'AT1G12220',
  'AT1G13680',
  'AT1G16420',
  'AT1G18350',
  'AT1G22070',
  'AT1G26630',
  'AT1G29690',
  'AT1G29850',
  'AT1G32230',
  'AT1G64280',
  'AT1G73260',
  'AT2G13810',
  'AT2G19860',
  'AT2G26560',
  'AT2G36010',
  'AT2G38530',
  'AT2G41060',
  'AT3G06490',
  'AT3G15010',
  'AT3G16770',
  'AT3G20210',
  'AT3G27060',
  'AT3G44880',
  'AT3G45860',
  'AT3G48090',
  'AT3G50930',
  'AT3G52430',
  'AT3G56400',
  'AT3G56860',
  'AT4G01370',
  'AT4G16890',
  'AT4G20380',
  'AT4G23130',
  'AT4G23170',
  'AT4G23280',
  'AT4G29130',
  'AT4G33680',
  'AT4G35790',
  'AT4G38360',
  'AT5G02190',
  'AT5G06950',
  'AT5G10380',
  'AT5G43940',
  'AT5G48485',
  'AT5G51200',
  'AT5G51290',
  'AT5G60600',
  'AT5G65600'},
 'GO:0012501 OR GO:0009861': {'AT1G06160',
  'AT1G08720',
  'AT1G12220',
  'AT1G13680',
  'AT1G16420',
  'AT1G26630',
  'AT1G29690',
  'AT1G29850',
  'AT1G32230',
  'AT1G44830',
  'AT1G48500',
  'AT1G64280',
  'AT1G73260',
  'AT2G19860',
  'AT2G26560',
  'AT2G36010',
  'AT2G38530',
  'AT2G39940',
  'AT2G41060',
  'AT2G46370',
  'AT3G01310',
  'AT3G06490',
  'AT3G14840',
  'AT3G15010',
  'AT3G16770',
  'AT3G20210',
  'AT3G27060',
  'AT3G44880',
  'AT3G45860',
  'AT3G50930',
  'AT3G56860',
  'AT4G01370',
  'AT4G16990',
  'AT4G23130',
  'AT4G23170',
  'AT4G23280',
  'AT4G29130',
  'AT4G35790',
  'AT4G38130',
  'AT4G38360',
  'AT5G02190',
  'AT5G10380',
  'AT5G43940',
  'AT5G44420',
  'AT5G51290'},
 'GO:0012501 OR GO:0034055': {'AT1G08720',
  'AT1G12220',
  'AT1G13680',
  'AT1G16420',
  'AT1G26630',
  'AT1G29690',
  'AT1G29850',
  'AT1G32230',
  'AT1G64280',
  'AT1G73260',
  'AT1G80280',
  'AT2G19860',
  'AT2G26560',
  'AT2G36010',
  'AT2G38530',
  'AT2G41060',
  'AT3G06490',
  'AT3G15010',
  'AT3G16770',
  'AT3G20210',
  'AT3G27060',
  'AT3G44880',
  'AT3G45860',
  'AT3G50930',
  'AT3G56860',
  'AT4G23130',
  'AT4G23170',
  'AT4G23280',
  'AT4G29130',
  'AT4G35790',
  'AT4G38360',
  'AT5G02190',
  'AT5G10380',
  'AT5G43940',
  'AT5G51290'},
 'GO:0012501 OR GO:0009682': {'AT1G08720',
  'AT1G12220',
  'AT1G13680',
  'AT1G16420',
  'AT1G18570',
  'AT1G26630',
  'AT1G29690',
  'AT1G29850',
  'AT1G32230',
  'AT1G32960',
  'AT1G64280',
  'AT1G64790',
  'AT1G73260',
  'AT2G19860',
  'AT2G22330',
  'AT2G26560',
  'AT2G30750',
  'AT2G30770',
  'AT2G36010',
  'AT2G38530',
  'AT2G41060',
  'AT2G44490',
  'AT3G06490',
  'AT3G15010',

In [11]:
transcriptome = pd.read_csv(
    "/Users/michael/Data/Luke_terrace_experiment/General_data/plate1_4_tpm_normalized.csv",
    index_col=0,
)
rows_to_drop_expression_data = [
    "A2450525897_n01_undetermined",
    "A2449446903_n01_undetermined",
    "B250508004_n01_undetermined",
    "B2449500127_n01_undetermined",
]
transcriptome = transcriptome.drop(index=rows_to_drop_expression_data)
transcriptome = transcriptome.sort_index()

In [12]:
metadata = pd.read_csv(
    "/Users/michael/Data/Luke_terrace_experiment/General_data/Plates_1_to_4_metadata_merged_luke.csv",
    index_col=0,
)
metadata = metadata.drop(
    columns=[
        "arb.sort",
        "sample-id",
        "Ambiguous Unstranded",
        "Ambiguous Forward",
        "Multimapping",
        "Unmapped Over Mapped",
    ]
)
metadata["Date and Time"] = metadata["date"] + " " + metadata["time"]
luke_time_data_format = "%-m/%-d/%y %-H:%-M"
metadata["Date and Time"] = pd.to_datetime(
    metadata["Date and Time"], format=luke_time_data_format
)


unusable_samples = [
    "A2450525897_n01_LICRNA01_A06",
    "A2450525897_n01_LICRNA01_A08",
    "A2450525897_n01_LICRNA01_C11",
    "A2450525897_n01_LICRNA01_D11",
    "A2450525897_n01_LICRNA01_D12",
    "A2449446903_n01_LICRNA02_F01",
    "B2449500127_n01_LICRNA04_A04",
    "B2449500127_n01_LICRNA04_A06",
    "B2449500127_n01_LICRNA04_A07",
]
borderline_unusable = [
    "A2450525897_n01_LICRNA01_F03",
    "A2450525897_n01_LICRNA01_G07",
    "A2449446903_n01_LICRNA02_A04",
    "A2449446903_n01_LICRNA02_H10",
    "B2449500127_n01_LICRNA04_H02",
    "B2449500127_n01_LICRNA04_H11",
]
all_unsable = borderline_unusable + unusable_samples

In [14]:
trimmed_transcriptome = transcriptome.drop(index=all_unsable)
trimmed_metadata = metadata.drop(index=all_unsable)
long_term_transcriptome = trimmed_transcriptome.loc[
    trimmed_metadata["Experiment Type"] == "Long Term"
]
long_term_metadata = trimmed_metadata.loc[
    trimmed_metadata["Experiment Type"] == "Long Term"
]

In [18]:
microbiome_abundance = pd.read_csv(
    "/Users/michael/Data/Luke_terrace_experiment/Microbiome/lic2024_16S_rab.csv"
)
long_term_microbiome = microbiome_abundance.merge(
    metadata[["sampID", "Experiment Type"]], left_on="plantID", right_on="sampID"
)
long_term_microbiome = long_term_microbiome.loc[
    long_term_microbiome["Experiment Type"] == "Long Term"
]
long_term_microbiome

,Sample,sample.type,timepoint,date,time,platename,daysincestart,plantID,Kingdom,Phylum,Class,Order,Family,Genus,Species,AbundR100,sampID,Experiment Type
1,LIC063,plant,t06,11/28/23,8:00,LIC_01,27,LIC063,d__Bacteria,Pseudomonadota,Alphaproteobacteria,Sphingomonadales,Sphingomonadaceae_486827,Sphingomonas_L_486704,Sphingomonas_L_486704 sp000786205,66.1,LIC063,Long Term
2,LIC159,plant,t14,1/23/24,8:00,LIC_02,83,LIC159,d__Bacteria,Cyanobacteriota,Cyanobacteriia,Cyanobacteriales,Coleofasciculaceae,Caldora,Caldora sp010672925,60.5,LIC159,Long Term
4,LIC306,plant,t26,3/8/24,8:00,LIC_04,128,LIC306,d__Bacteria,Pseudomonadota,Alphaproteobacteria,Sphingomonadales,Sphingomonadaceae_486827,Sphingomonas_L_486704,Sphingomonas_L_486704 sp000786205,57.2,LIC306,Long Term
5,LIC016,plant,t02,11/7/23,8:00,LIC_01,6,LIC016,d__Bacteria,Pseudomonadota,Alphaproteobacteria,Sphingomonadales,Sphingomonadaceae_486827,Sphingomonas_L_486704,Sphingomonas_L_486704 sp000786205,54.4,LIC016,Long Term
9,LIC051,plant,t05,11/21/23,8:00,LIC_01,20,LIC051,d__Bacteria,Pseudomonadota,Alphaproteobacteria,Rhizobiales_505101,Rhizobiaceae,Neorhizobium_500197,Neorhizobium soli,49.7,LIC051,Long Term
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12278,LIC157,plant,t14,1/23/24,8:00,LIC_02,83,LIC157,d__Bacteria,Actinomycetota,Actinomycetes,Propionibacteriales,Propionibacteriaceae,Friedmanniella,Friedmanniella luteola,0.5,LIC157,Long Term
12280,LIC195,plant,t17,2/2/24,8:00,LIC_03,93,LIC195,d__Bacteria,Actinomycetota,Actinomycetes,Propionibacteriales,Propionibacteriaceae,Friedmanniella,Friedmanniella flava,0.5,LIC195,Long Term
12281,LIC122,plant,t11,12/15/23,8:00,LIC_02,44,LIC122,d__Bacteria,Actinomycetota,Actinomycetes,Propionibacteriales,Nocardioidaceae,Nocardioides_A_392796,Nocardioides_A_392796 hankookensis,0.5,LIC122,Long Term
12282,LIC028,plant,t03,11/14/23,8:00,LIC_01,13,LIC028,d__Bacteria,Actinomycetota,Actinomycetes,Mycobacteriales,Geodermatophilaceae,Modestobacter,Modestobacter muralis,0.5,LIC028,Long Term
12285,LIC230,plant,t20,2/16/24,8:00,LIC_03,107,LIC230,d__Bacteria,Pseudomonadota,Alphaproteobacteria,Rhizobiales_505101,Beijerinckiaceae,Methylobacterium,Methylobacterium sp001424705,0.5,LIC230,Long Term

In [19]:
genus_sum = (
    long_term_microbiome[["Sample", "Genus", "AbundR100"]]
    .groupby(["Sample", "Genus"])
    .sum()
)
genus_sum = genus_sum.reset_index()

genus_sum_w_tp = genus_sum.merge(
    metadata[["sampID", "timepoint"]], left_on="Sample", right_on="sampID"
)
genus_sum_w_tp

      Sample                   Genus  AbundR100  sampID timepoint
0     LIC001       Actinomycetospora        0.6  LIC001       t01
1     LIC001            Actinoplanes        1.1  LIC001       t01
2     LIC001           Aeromicrobium        0.8  LIC001       t01
3     LIC001            Blastococcus        1.7  LIC001       t01
4     LIC001      Caulobacter_487784        0.5  LIC001       t01
...      ...                     ...        ...     ...       ...
5098  LIC368  Pseudoduganella_570666        0.5  LIC368       t08
5099  LIC368    Pseudomonas_E_647464        2.6  LIC368       t08
5100  LIC368            Rhodoferax_C        6.6  LIC368       t08
5101  LIC368   Sphingomonas_L_486704       19.7  LIC368       t08
5102  LIC368              Variovorax        1.3  LIC368       t08

[5103 rows x 5 columns]

In [20]:
all_present_genus = genus_sum_w_tp["Genus"].unique()
all_present_genus

array(['Actinomycetospora', 'Actinoplanes', 'Aeromicrobium',
       'Blastococcus', 'Caulobacter_487784', 'Chryseobacterium_A_796612',
       'Curtobacterium', 'Dactylopiibacterium', 'Flavobacterium',
       'Friedmanniella', 'Frigoribacterium', 'Geodermatophilus',
       'Herbaspirillum', 'Hylemonella', 'Kineococcus', 'Kineosporia',
       'Klenkia', 'Kordiimonas', 'Massilia_574544', 'Methylobacterium',
       'Methylophilus', 'Microbacterium_A_383321', 'Nakamurella',
       'Neorhizobium_500197', 'Nocardioides_A_392796',
       'Pseudoduganella_570666', 'Pseudomonas_B_650453',
       'Pseudomonas_E_647464', 'Pseudomonas_E_647626', 'Rhodoferax_C',
       'Solirubrobacter', 'Sphingomonas_L_486704', 'Telluria_573210',
       'Variovorax', 'Arthrobacter_E_385446', 'Arthrobacter_E_385777',
       'Caballeronia', 'Marmoricola_A_392027', 'Massilia_574424',
       'Microlunatus_B', 'Nocardioides_A_392805',
       'Noviherbaspirillum_A_568106', 'Paucimonas', 'Pedococcus',
       'Pseudoduganella_570662', 'Pseudoduganella_570691',
       'Rhizobium_C_501058', 'Rhodoglobus', 'Rugamonas_570800',
       'Aquabacterium_A_592457', 'Duganella_570917',
       'Janthinobacterium_571130', 'Janthinobacterium_571526',
       'Pelomonas', 'Aureimonas_A_501549', 'Devosia_A_502124',
       'Duganella_570715', 'Neorhizobium_500218', 'Pigmentiphaga',
       'Amnibacterium_382409', 'Buchnera', 'Ramlibacter_588642',
       'Brevundimonas', 'Alsobacter', 'Rathayibacter',
       'Herbiconiux_382276', 'Actinocorallia', 'Agrobacterium',
       'Amycolatopsis_D_380379', 'Asticcacaulis', 'Cellvibrio',
       'Herminiimonas_567389', 'Massilia_573596', 'Curvibacter_587305',
       'Modestobacter', 'Motilibacter_A', 'Pseudonocardia',
       'Methylotenera_A_557637', 'Mycobacterium', 'Cryptosporangium',
       'Caldora', 'Williamsia_A', 'Aureimonas_A_501548',
       'Marihabitans_390501', 'Noviherbaspirillum_A_568104',
       'Terracoccus', 'DSM-44207', 'UBA5216', 'Homoserinimonas_381256',
       'Bosea', 'Actinoallomurus', 'Baekduia', 'Belnapia',
       'Micromonospora_H_372070', 'Phenylobacterium', 'Gryllotalpicola',
       'Agrococcus', 'Pseudorhodoferax', 'Patulibacter', 'Aetherobacter',
       'Tardiphaga', 'Virgisporangium', 'Noviherbaspirillum_A_569121',
       'Pseudomonas_M', 'Labedella', 'Roseateles_592282', 'UBA1952',
       'Bradyrhizobium_503372', 'Aquabacterium_A_591266',
       'Roseomonas_507234', 'Inhella', 'Agreia', 'Abditibacterium',
       'Granulicoccus', 'Rhizobacter_590950', 'Aldersonia',
       'Xenophilus_587940', 'Paraburkholderia_580243',
       'Streptomyces_400150', 'Pseudokineococcus', 'Naasia_381491',
       'Arsenicicoccus', 'Ga0074137', 'Labilithrix',
       'Chryseobacterium_A_795111', 'Chioneia', 'Sphingomonas_R_483406',
       'Massilia_573446', 'Mesorhizobium_I', 'Umezawaea',
       'Croceibacterium_484881', 'Rhizorhabdus', 'Polaromonas',
       'Jatrophihabitans_A_372606', 'UBA4416', 'Allorhizobium_500053',
       'Herbiconiux_382278'], dtype=object)

In [21]:
## Need to fill in missing genus in every sample first
for sampID in genus_sum_w_tp["sampID"].unique():
    sampid_only_df = genus_sum_w_tp.loc[genus_sum_w_tp["sampID"] == sampID]
    present_genus_in_samp = sampid_only_df["Genus"].unique()
    difference_in_present_bacteria = list(
        set(all_present_genus) - set(present_genus_in_samp)
    )
    current_time_point = sampid_only_df["timepoint"].iloc[0]
    empty_df_to_add = pd.DataFrame(
        columns=["Sample", "Genus", "AbundR100", "sampID", "timepoint"]
    )
    empty_df_to_add["Genus"] = difference_in_present_bacteria
    empty_df_to_add["Sample"] = sampID
    empty_df_to_add["AbundR100"] = 0
    empty_df_to_add["sampID"] = sampID
    empty_df_to_add["timepoint"] = current_time_point
    genus_sum_w_tp = pd.concat([genus_sum_w_tp, empty_df_to_add])

In [23]:
genus_sum_w_tp

     Sample                      Genus  AbundR100  sampID timepoint
0    LIC001          Actinomycetospora        0.6  LIC001       t01
1    LIC001               Actinoplanes        1.1  LIC001       t01
2    LIC001              Aeromicrobium        0.8  LIC001       t01
3    LIC001               Blastococcus        1.7  LIC001       t01
4    LIC001         Caulobacter_487784        0.5  LIC001       t01
..      ...                        ...        ...     ...       ...
109  LIC368                  Labedella        0.0  LIC368       t08
110  LIC368  Jatrophihabitans_A_372606        0.0  LIC368       t08
111  LIC368     Pseudoduganella_570691        0.0  LIC368       t08
112  LIC368             Pseudonocardia        0.0  LIC368       t08
113  LIC368               Blastococcus        0.0  LIC368       t08

[30414 rows x 5 columns]

In [28]:
from scipy.stats import pearsonr, spearmanr

# Get Pseudomonas_E_647626 abundance for each sample (using 'Sample' which has LIC IDs)
pseudomonas_data = genus_sum_w_tp[genus_sum_w_tp["Genus"] == "Pseudomonas_E_647626"]
pseudomonas_abundance = pseudomonas_data.set_index("Sample")["AbundR100"]

# Get the mapping from filename to sampID (LIC IDs) from metadata
# We need samples that have both transcriptome data and Pseudomonas abundance
common_lic_ids = list(
    set(long_term_metadata["sampID"]) & set(pseudomonas_abundance.index)
)
common_filenames = long_term_metadata[
    long_term_metadata["sampID"].isin(common_lic_ids)
].index.tolist()

# Also filter to only those that are in the transcriptome
common_filenames = [f for f in common_filenames if f in long_term_transcriptome.index]

print(
    f"Found {len(common_filenames)} samples in common between transcriptome and microbiome data"
)

# Calculate correlation for each gene set combination
correlation_results = []

for combo_name, gene_set in filtered_combinations.items():
    # Get genes that are actually in the transcriptome
    genes_in_data = list(set(gene_set) & set(long_term_transcriptome.columns))

    if len(genes_in_data) == 0:
        continue

    # Calculate mean expression for these genes in each sample (using filename index)
    mean_expression = long_term_transcriptome.loc[common_filenames, genes_in_data].mean(
        axis=1
    )

    # Get corresponding Pseudomonas abundance (need to map filename to LIC ID)
    lic_ids = long_term_metadata.loc[common_filenames, "sampID"]
    pseudo_abund = pseudomonas_abundance.loc[lic_ids].values

    # Calculate correlations
    pearson_corr, pearson_pval = pearsonr(mean_expression.values, pseudo_abund)
    spearman_corr, spearman_pval = spearmanr(mean_expression.values, pseudo_abund)

    correlation_results.append(
        {
            "combination": combo_name,
            "n_genes_total": len(gene_set),
            "n_genes_in_data": len(genes_in_data),
            "pearson_r": pearson_corr,
            "pearson_pval": pearson_pval,
            "spearman_r": spearman_corr,
            "spearman_pval": spearman_pval,
        }
    )

# Convert to DataFrame and sort by absolute Pearson correlation
correlation_df = pd.DataFrame(correlation_results)
correlation_df["abs_pearson"] = correlation_df["pearson_r"].abs()
correlation_df = correlation_df.sort_values("abs_pearson", ascending=False)

print(f"\nAnalyzed {len(correlation_df)} gene set combinations")
print("\nTop 20 combinations by absolute Pearson correlation:")
print(correlation_df.head(20).to_string())

Found 214 samples in common between transcriptome and microbiome data

Analyzed 4077 gene set combinations

Top 20 combinations by absolute Pearson correlation:
                                                             combination  n_genes_total  n_genes_in_data  pearson_r  pearson_pval  spearman_r  spearman_pval  abs_pearson
0                                                             GO:0012501             34               34   0.223913      0.000973    0.219758       0.001214     0.223913
13                                              GO:0012501 OR GO:0034055             35               35   0.223692      0.000984    0.220402       0.001173     0.223692
17                                              GO:0012501 OR GO:0010421             35               35   0.222452      0.001052    0.219074       0.001258     0.222452
113                               GO:0012501 OR GO:0034055 OR GO:0010421             36               36   0.222235      0.001064    0.219719       0.001216     0.222235
9                                               GO:0012501 OR GO:0071219             41               41   0.220203      0.001186    0.220550       0.001164     0.220203
87                                GO:0012501 OR GO:0071219 OR GO:0034055             42               42   0.219969      0.001200    0.220890       0.001143     0.219969
91                                GO:0012501 OR GO:0071219 OR GO:0010421             42               42   0.218809      0.001276    0.219563       0.001226     0.218809
382                 GO:0012501 OR GO:0071219 OR GO:0034055 OR GO:0010421             43               43   0.218579      0.001292    0.219567       0.001226     0.218579
11                                              GO:0012501 OR GO:0009862             49               49   0.214799      0.001573    0.220771       0.001150     0.214799
100                               GO:0012501 OR GO:0009862 OR GO:0034055             50               50   0.214592      0.001590    0.220760       0.001151     0.214592
104                               GO:0012501 OR GO:0009862 OR GO:0010421             50               50   0.213589      0.001675    0.219443       0.001234     0.213589
418                 GO:0012501 OR GO:0009862 OR GO:0034055 OR GO:0010421             51               51   0.213385      0.001692    0.219453       0.001234     0.213385
85                                GO:0012501 OR GO:0071219 OR GO:0009862             56               56   0.211717      0.001843    0.216731       0.001423     0.211717
369                 GO:0012501 OR GO:0071219 OR GO:0009862 OR GO:0034055             57               57   0.211505      0.001863    0.216104       0.001470     0.211505
373                 GO:0012501 OR GO:0071219 OR GO:0009862 OR GO:0010421             57               57   0.210556      0.001955    0.215435       0.001522     0.210556
1008  GO:0012501 OR GO:0071219 OR GO:0009862 OR GO:0034055 OR GO:0010421             58               58   0.210347      0.001976    0.215441       0.001522     0.210347
7                                               GO:0012501 OR GO:0009626             84               84   0.202154      0.002971    0.194819       0.004227     0.202154
70                                GO:0012501 OR GO:0009626 OR GO:0034055             85               85   0.201946      0.003002    0.195147       0.004162     0.201946
74                                GO:0012501 OR GO:0009626 OR GO:0010421             85               85   0.201193      0.003114    0.194153       0.004362     0.201193
318                 GO:0012501 OR GO:0009626 OR GO:0034055 OR GO:0010421             86               86   0.200988      0.003145    0.194754       0.004240     0.200988

In [32]:
# Save top 20 combinations to CSV
top_20_combinations = correlation_df.head(20)[
    ["combination", "n_genes_total", "pearson_r"]
]
top_20_combinations.columns = ["combination", "genes_total", "pearson_R"]
top_20_combinations["pearson_R"] = top_20_combinations["pearson_R"].round(3)
top_20_combinations.to_csv(
    "/Users/michael/Data/Luke_terrace_experiment/General_data/Junk_data/top_20_gene_combinations.csv",
    index=False,
)
print(
    "/Users/michael/Data/Luke_terrace_experiment/General_data/Junk_data/Saved top 20 combinations to 'top_20_gene_combinations.csv'"
)

/Users/michael/Data/Luke_terrace_experiment/General_data/Junk_data/Saved top 20 combinations to 'top_20_gene_combinations.csv'

In [29]:
# Get all Pseudomonas genera (all genera that start with "Pseudomonas")
pseudomonas_genera = [g for g in all_present_genus if g.startswith("Pseudomonas")]
print(f"Found {len(pseudomonas_genera)} Pseudomonas genera:")
print(pseudomonas_genera)

# Get total Pseudomonas abundance for each sample by summing all Pseudomonas genera
all_pseudomonas_data = genus_sum_w_tp[genus_sum_w_tp["Genus"].isin(pseudomonas_genera)]
total_pseudomonas_abundance = all_pseudomonas_data.groupby("Sample")["AbundR100"].sum()

print(
    f"\nTotal Pseudomonas abundance range: {total_pseudomonas_abundance.min():.2f} to {total_pseudomonas_abundance.max():.2f}"
)

# Get common samples between transcriptome and microbiome data
common_lic_ids = list(
    set(long_term_metadata["sampID"]) & set(total_pseudomonas_abundance.index)
)
common_filenames = long_term_metadata[
    long_term_metadata["sampID"].isin(common_lic_ids)
].index.tolist()
common_filenames = [f for f in common_filenames if f in long_term_transcriptome.index]

print(
    f"\nFound {len(common_filenames)} samples in common between transcriptome and microbiome data"
)

# Calculate correlation for each gene set combination
correlation_results_total_pseudo = []

for combo_name, gene_set in filtered_combinations.items():
    # Get genes that are actually in the transcriptome
    genes_in_data = list(set(gene_set) & set(long_term_transcriptome.columns))

    if len(genes_in_data) == 0:
        continue

    # Calculate mean expression for these genes in each sample
    mean_expression = long_term_transcriptome.loc[common_filenames, genes_in_data].mean(
        axis=1
    )

    # Get corresponding total Pseudomonas abundance
    lic_ids = long_term_metadata.loc[common_filenames, "sampID"]
    pseudo_abund = total_pseudomonas_abundance.loc[lic_ids].values

    # Calculate correlations
    pearson_corr, pearson_pval = pearsonr(mean_expression.values, pseudo_abund)
    spearman_corr, spearman_pval = spearmanr(mean_expression.values, pseudo_abund)

    correlation_results_total_pseudo.append(
        {
            "combination": combo_name,
            "n_genes_total": len(gene_set),
            "n_genes_in_data": len(genes_in_data),
            "pearson_r": pearson_corr,
            "pearson_pval": pearson_pval,
            "spearman_r": spearman_corr,
            "spearman_pval": spearman_pval,
        }
    )

# Convert to DataFrame and sort by absolute Pearson correlation
correlation_df_total_pseudo = pd.DataFrame(correlation_results_total_pseudo)
correlation_df_total_pseudo["abs_pearson"] = correlation_df_total_pseudo[
    "pearson_r"
].abs()
correlation_df_total_pseudo = correlation_df_total_pseudo.sort_values(
    "abs_pearson", ascending=False
)

print(f"\nAnalyzed {len(correlation_df_total_pseudo)} gene set combinations")
print("\nTop 20 combinations by absolute Pearson correlation with total Pseudomonas:")
print(correlation_df_total_pseudo.head(20).to_string())

Found 4 Pseudomonas genera:
['Pseudomonas_B_650453', 'Pseudomonas_E_647464', 'Pseudomonas_E_647626', 'Pseudomonas_M']

Total Pseudomonas abundance range: 0.00 to 44.40

Found 214 samples in common between transcriptome and microbiome data

Analyzed 4077 gene set combinations

Top 20 combinations by absolute Pearson correlation with total Pseudomonas:
                                                                           combination  n_genes_total  n_genes_in_data  pearson_r  pearson_pval  spearman_r  spearman_pval  abs_pearson
64                                                            GO:0002237 OR GO:0010421             43               43   0.145684      0.033166    0.140847       0.039531     0.145684
278                                             GO:0009682 OR GO:0002237 OR GO:0010421             64               64   0.145255      0.033693    0.188126       0.005769     0.145255
772                               GO:0034055 OR GO:0009682 OR GO:0002237 OR GO:0010421             65               65   0.145118      0.033863    0.187606       0.005908     0.145118
60                                                            GO:0009682 OR GO:0002237             62               62   0.144964      0.034054    0.188065       0.005785     0.144964
271                                             GO:0034055 OR GO:0009682 OR GO:0002237             63               63   0.144827      0.034225    0.187890       0.005832     0.144827
6                                                                           GO:0002237             41               41   0.144669      0.034424    0.139551       0.041401     0.144669
703                               GO:0071219 OR GO:0009682 OR GO:0002237 OR GO:0010421             70               70   0.144420      0.034739    0.185529       0.006492     0.144420
275                                             GO:0034055 OR GO:0002237 OR GO:0010421             44               44   0.144392      0.034774    0.137067       0.045194     0.144392
1508                GO:0071219 OR GO:0034055 OR GO:0009682 OR GO:0002237 OR GO:0010421             71               71   0.144279      0.034918    0.185087       0.006623     0.144279
221                                             GO:0071219 OR GO:0009682 OR GO:0002237             68               68   0.144126      0.035114    0.185953       0.006369     0.144126
696                               GO:0071219 OR GO:0034055 OR GO:0009682 OR GO:0002237             69               69   0.143985      0.035295    0.185111       0.006616     0.143985
58                                                            GO:0034055 OR GO:0002237             42               42   0.143351      0.036119    0.136233       0.046532     0.143351
758                               GO:0009862 OR GO:0009682 OR GO:0002237 OR GO:0010421             77               77   0.140311      0.040295    0.179334       0.008553     0.140311
1558                GO:0009862 OR GO:0034055 OR GO:0009682 OR GO:0002237 OR GO:0010421             78               78   0.140164      0.040508    0.178958       0.008695     0.140164
256                                             GO:0009862 OR GO:0009682 OR GO:0002237             75               75   0.140004      0.040740    0.179647       0.008436     0.140004
751                               GO:0009862 OR GO:0034055 OR GO:0009682 OR GO:0002237             76               76   0.139856      0.040954    0.179407       0.008526     0.139856
1494                GO:0071219 OR GO:0009862 OR GO:0009682 OR GO:0002237 OR GO:0010421             83               83   0.139469      0.041522    0.176443       0.009700     0.139469
2454  GO:0071219 OR GO:0009862 OR GO:0034055 OR GO:0009682 OR GO:0002237 OR GO:0010421             84               84   0.139318      0.041745    0.176042       0.009869     0.139318
680                               GO:0071219 OR GO:0009862 OR GO:0009682 OR GO:0002237             81               81   0.139158      0.041983    0.176513       0.009671     0.139158
1487                GO:0071219 OR GO:0009862 OR GO:0034055 OR GO:0009682 OR GO:0002237             82               82   0.139007      0.042208    0.176417       0.009711     0.139007