In [1]:
import pandas as pd
import numpy as np

In [3]:
luke_original_meta = pd.read_csv(
    "/Users/michael/Git/Outdoor_microbiome/Local_analysis/Converting_plates_to_normal_format/Plate1_guide.csv",
    sep="\t",
)
luke_original_meta

,filename,plate.pos,arb.sort,sampID,sample.type,timepoint,date,time,extractplate,rnaprepplate
0,A2450525897_n01_LICRNA01_A01.fastq.gz,A01,1,LIC001,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01
1,A2450525897_n01_LICRNA01_B01.fastq.gz,B01,2,LIC002,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01
2,A2450525897_n01_LICRNA01_C01.fastq.gz,C01,3,LIC003,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01
3,A2450525897_n01_LICRNA01_D01.fastq.gz,D01,4,LIC004,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01
4,A2450525897_n01_LICRNA01_E01.fastq.gz,E01,5,LIC005,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01
...,...,...,...,...,...,...,...,...,...,...
379,B2449500127_n01_LICRNA04_D12.fastq.gz,D12,92,LIC640,plant,c2_t06,3/2/24,16:00,LICCIRC_03,LICRNA_04
380,B2449500127_n01_LICRNA04_E12.fastq.gz,E12,93,LIC641,plant,c2_t06,3/2/24,16:00,LICCIRC_03,LICRNA_04
381,B2449500127_n01_LICRNA04_F12.fastq.gz,F12,94,LIC642,plant,c2_t06,3/2/24,16:00,LICCIRC_03,LICRNA_04
382,B2449500127_n01_LICRNA04_G12.fastq.gz,G12,95,LIC643,plant,c2_t06,3/2/24,16:00,LICCIRC_03,LICRNA_04
383,B2449500127_n01_LICRNA04_H12.fastq.gz,H12,96,LIC644,plant,c2_t06,3/2/24,16:00,LICCIRC_03,LICRNA_04

In [4]:
luke_new_meta = pd.read_csv(
    "/Users/michael/Git/Outdoor_microbiome/Local_analysis/Converting_plates_to_normal_format/licrna5_meta.csv"
)
luke_new_meta

,filename,plate.pos,arb.sort,sampID,sample.type,timepoint,date,time,extractplate,rnaprepplate
0,A2534491401_n01_LICRNA05_A01,A01,1,LIC673,plant,c2_t07,3/2/24,20:00,LICCIRC_04,LICRNA_05
1,A2534491401_n01_LICRNA05_B01,B01,2,LIC674,plant,c2_t07,3/2/24,20:00,LICCIRC_04,LICRNA_05
2,A2534491401_n01_LICRNA05_C01,C01,3,LIC675,plant,c2_t07,3/2/24,20:00,LICCIRC_04,LICRNA_05
3,A2534491401_n01_LICRNA05_D01,D01,4,LIC676,plant,c2_t07,3/2/24,20:00,LICCIRC_04,LICRNA_05
4,A2534491401_n01_LICRNA05_E01,E01,5,LIC677,plant,c2_t07,3/2/24,20:00,LICCIRC_04,LICRNA_05
...,...,...,...,...,...,...,...,...,...,...
91,A2534491401_n01_LICRNA05_D12,D12,92,LIC542,plant,c1_t13,2/11/24,20:00,LICCIRC_02,LICRNA_05
92,A2534491401_n01_LICRNA05_E12,E12,93,LIC495,plant,c1_t09,2/11/24,4:00,LICCIRC_02,LICRNA_05
93,A2534491401_n01_LICRNA05_F12,F12,94,LIC421,plant,c1_t04,2/10/24,8:00,LICCIRC_01,LICRNA_05
94,A2534491401_n01_LICRNA05_G12,G12,95,LIC493,plant,c1_t09,2/11/24,4:00,LICCIRC_02,LICRNA_05
95,A2534491401_n01_LICRNA05_H12,H12,96,LIC505,plant,c1_t10,2/11/24,8:00,LICCIRC_02,LICRNA_05

In [13]:
merged_luke_data = pd.concat([luke_original_meta, luke_new_meta], ignore_index=True)
merged_luke_data

,filename,plate.pos,arb.sort,sampID,sample.type,timepoint,date,time,extractplate,rnaprepplate
0,A2450525897_n01_LICRNA01_A01.fastq.gz,A01,1,LIC001,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01
1,A2450525897_n01_LICRNA01_B01.fastq.gz,B01,2,LIC002,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01
2,A2450525897_n01_LICRNA01_C01.fastq.gz,C01,3,LIC003,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01
3,A2450525897_n01_LICRNA01_D01.fastq.gz,D01,4,LIC004,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01
4,A2450525897_n01_LICRNA01_E01.fastq.gz,E01,5,LIC005,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01
...,...,...,...,...,...,...,...,...,...,...
475,A2534491401_n01_LICRNA05_D12,D12,92,LIC542,plant,c1_t13,2/11/24,20:00,LICCIRC_02,LICRNA_05
476,A2534491401_n01_LICRNA05_E12,E12,93,LIC495,plant,c1_t09,2/11/24,4:00,LICCIRC_02,LICRNA_05
477,A2534491401_n01_LICRNA05_F12,F12,94,LIC421,plant,c1_t04,2/10/24,8:00,LICCIRC_01,LICRNA_05
478,A2534491401_n01_LICRNA05_G12,G12,95,LIC493,plant,c1_t09,2/11/24,4:00,LICCIRC_02,LICRNA_05
479,A2534491401_n01_LICRNA05_H12,H12,96,LIC505,plant,c1_t10,2/11/24,8:00,LICCIRC_02,LICRNA_05

In [14]:
merged_luke_data.loc[merged_luke_data.duplicated(subset="sampID", keep="last")]

,filename,plate.pos,arb.sort,sampID,sample.type,timepoint,date,time,extractplate,rnaprepplate
3,A2450525897_n01_LICRNA01_D01.fastq.gz,D01,4,LIC004,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01
6,A2450525897_n01_LICRNA01_G01.fastq.gz,G01,7,LIC007,plant,t01,11/1/23,8:00,LIC_01,LICRNA_01
8,A2450525897_n01_LICRNA01_A02.fastq.gz,A02,9,LIC013,plant,t02,11/7/23,8:00,LIC_01,LICRNA_01
10,A2450525897_n01_LICRNA01_C02.fastq.gz,C02,11,LIC015,plant,t02,11/7/23,8:00,LIC_01,LICRNA_01
15,A2450525897_n01_LICRNA01_H02.fastq.gz,H02,16,LIC020,plant,t02,11/7/23,8:00,LIC_01,LICRNA_01
21,A2450525897_n01_LICRNA01_F03.fastq.gz,F03,22,LIC030,plant,t03,11/14/23,8:00,LIC_01,LICRNA_01
38,A2450525897_n01_LICRNA01_G05.fastq.gz,G05,39,LIC055,plant,t05,11/21/23,8:00,LIC_01,LICRNA_01
40,A2450525897_n01_LICRNA01_A06.fastq.gz,A06,41,LIC061,plant,t06,11/28/23,8:00,LIC_01,LICRNA_01
54,A2450525897_n01_LICRNA01_G07.fastq.gz,G07,55,LIC079,plant,t07,12/1/23,8:00,LIC_01,LICRNA_01
56,A2450525897_n01_LICRNA01_A08.fastq.gz,A08,57,LIC097,plant,t09,12/8/23,8:00,LIC_02,LICRNA_01
82,A2450525897_n01_LICRNA01_C11.fastq.gz,C11,83,LIC135,plant,t12,1/5/24,8:00,LIC_02,LICRNA_01
83,A2450525897_n01_LICRNA01_D11.fastq.gz,D11,84,LIC136,plant,t12,1/5/24,8:00,LIC_02,LICRNA_01
91,A2450525897_n01_LICRNA01_D12.fastq.gz,D12,92,LIC148,plant,t13,1/15/24,8:00,LIC_02,LICRNA_01
96,A2449446903_n01_LICRNA02_A01.fastq.gz,A01,1,LIC157,plant,t14,1/23/24,8:00,LIC_02,LICRNA_02
101,A2449446903_n01_LICRNA02_F01.fastq.gz,F01,6,LIC162,plant,t14,1/23/24,8:00,LIC_02,LICRNA_02
120,A2449446903_n01_LICRNA02_A04.fastq.gz,A04,25,LIC205,plant,t18,2/6/24,8:00,LIC_03,LICRNA_02
152,A2449446903_n01_LICRNA02_A08.fastq.gz,A08,57,LIC253,plant,t22,2/23/24,8:00,LIC_03,LICRNA_02
170,A2449446903_n01_LICRNA02_C10.fastq.gz,C10,75,LIC291,plant,t25,3/5/24,8:00,LIC_04,LICRNA_02
174,A2449446903_n01_LICRNA02_G10.fastq.gz,G10,79,LIC295,plant,t25,3/5/24,8:00,LIC_04,LICRNA_02
175,A2449446903_n01_LICRNA02_H10.fastq.gz,H10,80,LIC296,plant,t25,3/5/24,8:00,LIC_04,LICRNA_02
207,B250508004_n01_LICRNA03_H02.fastq.gz,H02,16,LIC344,plant,t24,3/1/24,8:00,LIC_04,LICRNA_03
209,B250508004_n01_LICRNA03_B03.fastq.gz,B03,18,LIC350,plant,t16,1/30/24,8:00,LIC_04,LICRNA_03
224,B250508004_n01_LICRNA03_A05.fastq.gz,A05,33,LIC385,plant,c1_t01,2/9/24,20:00,LICCIRC_01,LICRNA_03
248,B250508004_n01_LICRNA03_A08.fastq.gz,A08,57,LIC421,plant,c1_t04,2/10/24,8:00,LICCIRC_01,LICRNA_03
256,B250508004_n01_LICRNA03_A09.fastq.gz,A09,65,LIC433,plant,c1_t05,2/10/24,12:00,LICCIRC_01,LICRNA_03
271,B250508004_n01_LICRNA03_H10.fastq.gz,H10,80,LIC452,plant,c1_t06,2/10/24,16:00,LICCIRC_01,LICRNA_03
280,B250508004_n01_LICRNA03_A12.fastq.gz,A12,89,LIC481,plant,c1_t08,2/11/24,0:00,LICCIRC_02,LICRNA_03
281,B250508004_n01_LICRNA03_B12.fastq.gz,B12,90,LIC482,plant,c1_t08,2/11/24,0:00,LICCIRC_02,LICRNA_03
282,B250508004_n01_LICRNA03_C12.fastq.gz,C12,91,LIC483,plant,c1_t08,2/11/24,0:00,LICCIRC_02,LICRNA_03
283,B250508004_n01_LICRNA03_D12.fastq.gz,D12,92,LIC484,plant,c1_t08,2/11/24,0:00,LICCIRC_02,LICRNA_03
284,B250508004_n01_LICRNA03_E12.fastq.gz,E12,93,LIC485,plant,c1_t08,2/11/24,0:00,LICCIRC_02,LICRNA_03
285,B250508004_n01_LICRNA03_F12.fastq.gz,F12,94,LIC486,plant,c1_t08,2/11/24,0:00,LICCIRC_02,LICRNA_03
286,B250508004_n01_LICRNA03_G12.fastq.gz,G12,95,LIC487,plant,c1_t08,2/11/24,0:00,LICCIRC_02,LICRNA_03
287,B250508004_n01_LICRNA03_H12.fastq.gz,H12,96,LIC488,plant,c1_t08,2/11/24,0:00,LICCIRC_02,LICRNA_03
289,B2449500127_n01_LICRNA04_B01.fastq.gz,B01,2,LIC482,plant,c1_t08,2/11/24,0:00,LICCIRC_02,LICRNA_04
293,B2449500127_n01_LICRNA04_F01.fastq.gz,F01,6,LIC486,plant,c1_t08,2/11/24,0:00,LICCIRC_02,LICRNA_04
296,B2449500127_n01_LICRNA04_A02.fastq.gz,A02,9,LIC493,plant,c1_t09,2/11/24,4:00,LICCIRC_02,LICRNA_04
298,B2449500127_n01_LICRNA04_C02.fastq.gz,C02,11,LIC495,plant,c1_t09,2/11/24,4:00,LICCIRC_02,LICRNA_04
304,B2449500127_n01_LICRNA04_A03.fastq.gz,A03,17,LIC505,plant,c1_t10,2/11/24,8:00,LICCIRC_02,LICRNA_04
305,B2449500127_n01_LICRNA04_B03.fastq.gz,B03,18,LIC506,plant,c1_t10,2/11/24,8:00,LICCIRC_02,LICRNA_04
308,B2449500127_n01_LICRNA04_E03.fastq.gz,E03,21,LIC509,plant,c1_t10,2/11/24,8:00,LICCIRC_02,LICRNA_04
312,B2449500127_n01_LICRNA04_A04.fastq.gz,A04,25,LIC517,plant,c1_t11,2/11/24,12:00,LICCIRC_02,LICRNA_04
328,B2449500127_n01_LICRNA04_A06.fastq.gz,A06,41,LIC541,plant,c1_t13,2/11/24,20:00,LICCIRC_02,LICRNA_04
329,B2449500127_n01_LICRNA04_B06.fastq.gz,B06,42,LIC542,plant,c1_t13,2/11/24,20:00,LICCIRC_02,LICRNA_04
336,B2449500127_n01_LICRNA04_A07.fastq.gz,A07,49,LIC577,plant,c2_t01,3/1/24,20:00,LICCIRC_03,LICRNA_04
337,B2449500127_n01_LICRNA04_B07.fastq.gz,B07,50,LIC578,plant,c2_t01,3/1/24,20:00,LICCIRC_03,LICRNA_04
375,B2449500127_n01_LICRNA04_H11.fastq.gz,H11,88,LIC632,plant,c2_t05,3/2/24,12:00,LICCIRC_03,LICRNA_04
444,A2534491401_n01_LICRNA05_E08,E08,61,LIC148,plant,t13,1/15/24,8:00,LIC_02,LICRNA_05

In [18]:
luke_new_meta.loc[luke_new_meta.duplicated(subset="sampID", keep=False)]

,filename,plate.pos,arb.sort,sampID,sample.type,timepoint,date,time,extractplate,rnaprepplate
60,A2534491401_n01_LICRNA05_E08,E08,61,LIC148,plant,t13,1/15/24,8:00,LIC_02,LICRNA_05
82,A2534491401_n01_LICRNA05_C11,C11,83,LIC148,plant,t13,1/15/24,8:00,LIC_02,LICRNA_05

In [17]:
merged_luke_data.loc[merged_luke_data["sampID"] == "LIC148"]

,filename,plate.pos,arb.sort,sampID,sample.type,timepoint,date,time,extractplate,rnaprepplate
91,A2450525897_n01_LICRNA01_D12.fastq.gz,D12,92,LIC148,plant,t13,1/15/24,8:00,LIC_02,LICRNA_01
444,A2534491401_n01_LICRNA05_E08,E08,61,LIC148,plant,t13,1/15/24,8:00,LIC_02,LICRNA_05
466,A2534491401_n01_LICRNA05_C11,C11,83,LIC148,plant,t13,1/15/24,8:00,LIC_02,LICRNA_05

In [ ]:
merged_luke_data.to_csv(
    "/Users/michael/Git/Outdoor_microbiome/Local_analysis/Converting_plates_to_normal_format/Plates_1_to_5_just_merged.csv"
)